backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: gbarboza12/lguide # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: date, label: Date, widget: date }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", 
          options: ["Books", "Films", "Social Media", "Podcasts"]}
      - {label: "Tags", hint: "Separate each tag with a comma", name: "tags", widget: "list"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured image", name: "image", widget: "image", required: false}